# Generated by Django 5.0.1 on 2024-01-28 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='content',
            new_name='desciption',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='car',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
    ]
